#!/usr/bin/env bash
set -e
npm run clean
FIX=true npm run lint
VERBOSE=true npm run test
cd engine
cargo fmt
cargo clippy
cargo test
cd -
npm run build
npm run test:functional
tarball_path=$(npm pack)
mkdir -p dist
tarball_dest="dist/${tarball_path}"
[[ -f "$tarball_dest" ]] && rm "$tarball_dest"
mv "$tarball_path" "$tarball_dest"
