#!/usr/bin/env bash
set -e
cd engine
cargo fmt
cargo clippy
cd -
npm run test:all
tarball_path=$(npm pack)
mkdir -p dist
tarball_dest="dist/${tarball_path}"
[[ -f "$tarball_dest" ]] && rm "$tarball_dest"
mv "$tarball_path" "$tarball_dest"
